wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
num_train_epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684085227.893132
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.2
      6: 4.29.1
      8:
      - 1
      - 5
